import React from 'react';
import { format } from 'date-fns';
import logo from '../../assets/logo.png';
import mcaLogo from '../../assets/mca21logo.png';

interface ReportTemplateProps {
  title?: string;
  subtitle?: string;
  generatedBy?: string;
  children: React.ReactNode;
}

const ReportTemplate = React.forwardRef<HTMLDivElement, ReportTemplateProps>(
  ({ title = 'System Report', subtitle, generatedBy = 'Lok-Vaani Admin', children }, ref) => {
    return (
      <div className="bg-gray-100 p-8 min-h-screen flex justify-center hidden-on-screen">
        {/* The Printable Area */}
        <div
          ref={ref}
          className="bg-white shadow-lg relative"
          style={{
            width: '210mm', // Force A4 width
            minHeight: '297mm', // Minimum A4 height
            padding: '15mm', // Slightly reduced padding to maximize space
            boxSizing: 'border-box',
            margin: '0 auto',
            fontFamily: '"Times New Roman", Times, serif', // More formal font for reports
          }}
        >
          {/* Watermark */}
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none opacity-[0.03] z-0">
             <img src={logo} alt="Watermark" className="w-[80%]" />
          </div>

          <div className="relative z-10 flex flex-col gap-6">
            {/* Header Section */}
            <header data-pdf-section="header" className="border-b-4 border-[#0846AA] pb-6 mb-4 flex justify-between items-end">
              <div className="flex flex-col">
                <h1 className="text-4xl font-bold text-[#0846AA] uppercase tracking-wide leading-tight">
                  {title}
                </h1>
                {subtitle && (
                  <p className="text-gray-600 mt-2 text-xl italic font-light">
                    {subtitle}
                  </p>
                )}
              </div>
              <div className="flex flex-col items-end gap-2">
                <div className="flex items-center gap-4">
                  <img src={mcaLogo} alt="MCA Logo" className="h-16 object-contain" />
                  <div className="h-12 w-px bg-gray-300"></div>
                  <img src={logo} alt="Lok-Vaani Logo" className="h-14 object-contain" />
                </div>
                <div className="text-sm text-gray-500 mt-2 font-semibold">
                  {format(new Date(), 'MMMM do, yyyy')}
                </div>
              </div>
            </header>

            {/* Content Container - Children will be captured individually by the exporter */}
            <main className="flex flex-col gap-8">
              {React.Children.map(children, (child, index) => (
                <div key={index} data-pdf-section className="report-section break-inside-avoid">
                  {child}
                </div>
              ))}
            </main>

            {/* Footer Placeholder (Visual only, real footer added by PDF generator usually) */}
            <div data-pdf-section="footer" className="mt-12 pt-4 border-t border-gray-200 text-center text-xs text-gray-400 flex justify-between items-center">
               <span>Generated by {generatedBy}</span>
               <span>Confidential - For Internal Use Only</span>
            </div>
          </div>
        </div>
      </div>
    );
  }
);

ReportTemplate.displayName = 'ReportTemplate';

export default ReportTemplate;
